from pathlib import Path
from typing import Any

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


def _safe_float(value: Any, fallback: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return fallback


def _metric(item: dict[str, Any], key: str, fallback: Any = 0) -> Any:
    metrics = item.get("metrics") or {}
    return metrics.get(key, item.get(key, fallback))


def _best_by_metric(
    results: list[dict[str, Any]],
    key: str,
    reverse: bool = True,
) -> dict[str, Any] | None:
    if not results:
        return None

    return sorted(
        results,
        key=lambda item: _safe_float(_metric(item, key)),
        reverse=reverse,
    )[0]


def _similarity_label(ratio: float) -> str:
    if ratio == 0:
        return "Completely Different"
    if ratio < 0.25:
        return "Highly Different"
    if ratio < 0.60:
        return "Moderately Similar"
    return "Highly Similar"


def _latency_us(item: dict[str, Any]) -> int:
    metrics = item.get("metrics") or {}
    return int(_safe_float(metrics.get("latency_seconds")) * 1_000_000)


def build_pdf_report(data: dict[str, Any], output_path: str | Path) -> Path:
    doc = SimpleDocTemplate(
        str(output_path),
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36,
    )

    styles = getSampleStyleSheet()
    elements = []

    results = data.get("results", []) or []
    pairwise = data.get("pairwise_comparisons", []) or []

    elements.append(Paragraph("Tokenizer Evaluation Report", styles["Heading1"]))
    elements.append(Spacer(1, 6))
    elements.append(Paragraph("Generated by Tokenizer Evaluation Engine", styles["Normal"]))
    elements.append(Spacer(1, 16))

    if results:
        best_eff = _best_by_metric(results, "efficiency_score")
        fastest = _best_by_metric(results, "latency_seconds", reverse=False)
        shortest = _best_by_metric(results, "token_count", reverse=False)
        granular = _best_by_metric(results, "token_count", reverse=True)

        elements.append(Paragraph("<b>Executive Summary</b>", styles["Heading2"]))
        elements.append(Spacer(1, 6))

        summary_lines = [
            f"Best overall tokenizer: {best_eff.get('tokenizer_name') if best_eff else '-'}",
            f"Fastest tokenizer: {fastest.get('tokenizer_name') if fastest else '-'}",
            f"Shortest sequence: {shortest.get('tokenizer_name') if shortest else '-'}",
            f"Most granular: {granular.get('tokenizer_name') if granular else '-'}",
        ]

        for line in summary_lines:
            elements.append(Paragraph(f"• {line}", styles["Normal"]))
            elements.append(Spacer(1, 3))

        elements.append(Spacer(1, 14))

    elements.append(Paragraph("<b>Source Text</b>", styles["Heading2"]))
    elements.append(Spacer(1, 6))
    elements.append(Paragraph(data.get("text", "-"), styles["Normal"]))
    elements.append(Spacer(1, 18))

    elements.append(Paragraph("<b>Summary Table</b>", styles["Heading2"]))
    elements.append(Spacer(1, 8))

    table_data = [["Tokenizer", "Tokens", "Unique", "Eff.", "Latency (µs)", "Comp."]]

    for item in results:
        table_data.append(
            [
                item.get("tokenizer_name", "-"),
                _metric(item, "token_count"),
                _metric(item, "unique_token_count"),
                round(_safe_float(_metric(item, "efficiency_score")), 2),
                _latency_us(item),
                round(_safe_float(_metric(item, "compression_ratio")), 2),
            ]
        )

    table = Table(table_data, hAlign="LEFT")

    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F3B73")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ALIGN", (1, 1), (-1, -1), "CENTER"),
                (
                    "ROWBACKGROUNDS",
                    (0, 1),
                    (-1, -1),
                    [colors.whitesmoke, colors.HexColor("#EEF2F7")],
                ),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("PADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )

    elements.append(table)
    elements.append(Spacer(1, 18))

    elements.append(Paragraph("<b>Interpretation</b>", styles["Heading2"]))
    elements.append(Spacer(1, 6))

    if not results:
        elements.append(Paragraph("No interpretation available.", styles["Normal"]))
        elements.append(Spacer(1, 14))
    else:
        lowest = _best_by_metric(results, "token_count", reverse=False)
        highest = _best_by_metric(results, "token_count", reverse=True)
        best_eff = _best_by_metric(results, "efficiency_score")
        fastest = _best_by_metric(results, "latency_seconds", reverse=False)

        if lowest:
            elements.append(
                Paragraph(
                    f"The <b>{lowest.get('tokenizer_name')}</b> tokenizer produces the most compact "
                    f"representation with <b>{_metric(lowest, 'token_count')}</b> tokens.",
                    styles["Normal"],
                )
            )
            elements.append(Spacer(1, 4))

        if highest:
            elements.append(
                Paragraph(
                    f"The <b>{highest.get('tokenizer_name')}</b> tokenizer provides the most granular "
                    f"segmentation, producing <b>{_metric(highest, 'token_count')}</b> tokens.",
                    styles["Normal"],
                )
            )
            elements.append(Spacer(1, 4))

        if best_eff:
            elements.append(
                Paragraph(
                    f"The <b>{best_eff.get('tokenizer_name')}</b> tokenizer achieves the highest efficiency "
                    f"score (<b>{round(_safe_float(_metric(best_eff, 'efficiency_score')), 2)}</b>), "
                    "indicating stronger compression behavior per token.",
                    styles["Normal"],
                )
            )
            elements.append(Spacer(1, 4))

        if fastest:
            elements.append(
                Paragraph(
                    f"The fastest tokenizer is <b>{fastest.get('tokenizer_name')}</b> "
                    f"with <b>{_latency_us(fastest)} µs</b> latency.",
                    styles["Normal"],
                )
            )
            elements.append(Spacer(1, 4))

        elements.append(
            Paragraph(
                "Overall, tokenizer selection directly impacts sequence length, computational cost, "
                "semantic granularity, compression behavior, and downstream model efficiency.",
                styles["Normal"],
            )
        )
        elements.append(Spacer(1, 14))

    elements.append(Paragraph("<b>Recommendation</b>", styles["Heading2"]))
    elements.append(Spacer(1, 6))

    recommendations = {
        "word": "Best for compression and readability",
        "byte": "Best for ultra-fast tokenization",
        "char": "Best for debugging and maximum granularity",
        "bpe": "Balanced option between compression and flexibility",
        "byte_bpe": "Best for handling complex or unseen text",
        "regex": "Best for custom tokenization patterns and domain-specific text",
        "regex_bpe": "Best for custom tokenization patterns and domain-specific text",
    }

    for item in results:
        name = item.get("tokenizer_name", "").lower()
        if name in recommendations:
            elements.append(Paragraph(f"• {name}: {recommendations[name]}", styles["Normal"]))
            elements.append(Spacer(1, 3))

    elements.append(Spacer(1, 14))

    elements.append(Paragraph("<b>Tokenizer Details</b>", styles["Heading2"]))
    elements.append(Spacer(1, 10))

    for item in results:
        elements.append(Paragraph(f"<b>{item.get('tokenizer_name', '-')}</b>", styles["Normal"]))
        elements.append(Spacer(1, 4))

        details = [
            f"Tokens: {_metric(item, 'token_count')}",
            f"Unique: {_metric(item, 'unique_token_count')}",
            f"Efficiency: {round(_safe_float(_metric(item, 'efficiency_score')), 2)}",
            f"Latency: {_latency_us(item)} µs",
        ]

        for detail in details:
            elements.append(Paragraph(detail, styles["Normal"]))
            elements.append(Spacer(1, 2))

        elements.append(Spacer(1, 10))

    if pairwise:
        elements.append(Paragraph("<b>Pairwise Comparisons</b>", styles["Heading2"]))
        elements.append(Spacer(1, 8))

        for item in pairwise:
            ratio = _safe_float(item.get("overlap_ratio"))

            elements.append(
                Paragraph(
                    f"<b>{item.get('left_name', '-')} ↔ {item.get('right_name', '-')}</b>",
                    styles["Normal"],
                )
            )
            elements.append(Spacer(1, 3))
            elements.append(Paragraph(f"Overlap Ratio: {round(ratio, 2)}", styles["Normal"]))
            elements.append(Paragraph(f"Similarity Level: {_similarity_label(ratio)}", styles["Normal"]))
            elements.append(Spacer(1, 10))

    doc.build(elements)

    return Path(output_path)